package view.usuario;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Akira
 */
public class TelaUsuarioInicial extends javax.swing.JPanel {

    /**
     * Creates new form TelaUsuarioInicial
     */
    public TelaUsuarioInicial() {
        initComponents();
        
        // Incializa a lista de Musicas
        DefaultListModel<String> modeloPrincipal = new DefaultListModel<>();
        listaMusicas.setModel(modeloPrincipal);
        
        // Inicializa a lsita de playlist
        DefaultListModel<String> modeloPlaylist = new DefaultListModel<>();
        listaPlaylist.setModel(modeloPlaylist);
        
    }
    
    public void setController(ActionListener controller) {
        // botoes na parte de cima
        btnMenu.setActionCommand("Menu");
        btnMenu.addActionListener(controller);
        
        // botoes na parte lateral
        btnInicio.setActionCommand("Inicio");
        btnInicio.addActionListener(controller);
        btnPlaylist.setActionCommand("Playlist");
        btnPlaylist.addActionListener(controller);
        btnHistorico.setActionCommand("Historico");
        btnHistorico.addActionListener(controller);
        
        // botoes na tela principal
        btnAddMusicaPlaylist.setActionCommand("Add musica playlist");
        btnAddMusicaPlaylist.addActionListener(controller);
        btnRemoverMusicaPlaylist.setActionCommand("Rmv musica playlist");
        btnRemoverMusicaPlaylist.addActionListener(controller);
        
        // botoes na parte de baixo
        btnDeslike.setActionCommand("Deslike");
        btnDeslike.addActionListener(controller);
        btnLike.setActionCommand("Like");
        btnLike.addActionListener(controller);
        btnPlayPause.setActionCommand("PlayPause");
        btnPlayPause.addActionListener(controller);
        btnProximo.setActionCommand("Proximo");
        btnProximo.addActionListener(controller);
        btnVoltar.setActionCommand("Voltar");
        btnVoltar.addActionListener(controller);   
    }
    
    // LISTENER DO CAMPO DE BUSCA DE MUSICA
    public void listenerBusca (DocumentListener listener){
        txtfieldPesquisa.getDocument().addDocumentListener(listener);
    }
    public String getCampoBuscador(){
        return txtfieldPesquisa.getText();
    }
    
    // LISTA DE MUSICA
    public void limparListaMusicas(){
        // Limpa a lista 
        DefaultListModel<String> lista = (DefaultListModel<String>) listaMusicas.getModel();
        lista.clear();
    }
    public void addListaMusica(String musica){
        // Limpa a lista 
        DefaultListModel<String> lista = (DefaultListModel<String>) listaMusicas.getModel();
        lista.addElement(musica);
    }
    public int getMusicaSelecionada() {
        return listaMusicas.getSelectedIndex() - 1;
    }
    
    // LISTA DE PLAYLIST
    public void limparListaPlaylist(){
        // Limpa a lista 
        DefaultListModel<String> lista = (DefaultListModel<String>) listaPlaylist.getModel();
        lista.clear();
    }
    public void addListaPlaylist(String nome){
        // Limpa a lista 
        DefaultListModel<String> lista = (DefaultListModel<String>) listaPlaylist.getModel();
        lista.addElement(nome);
    }
    public int getPlaylistSelecionada() {
        return listaPlaylist.getSelectedIndex() - 1;
    }

    // SET DOS TEXTO DA DIREITA
    public void setInfoTitulo(String titulo){txtInfoTitulo.setText(titulo);}
    public void setInfoArtista(String artista){txtInfoTitulo.setText(artista);}
    public void setInfoGenero(String genero){txtInfoTitulo.setText(genero);}
    public void setInfoDuracao(int duracao){
        int minutos = duracao / 60;
        int segundos = duracao % 60;
        String duracaoFormatada = String.format("%-2d/%-2d", minutos, segundos);
        txtInfoTitulo.setText(duracaoFormatada);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCima = new javax.swing.JPanel();
        pngSpotifei = new javax.swing.JLabel();
        txtBemVindo = new javax.swing.JLabel();
        txtfieldPesquisa = new javax.swing.JTextField();
        jpnPlaylist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPlaylist = new javax.swing.JList<>();
        txtPlaylist = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        txtPlaylist1 = new javax.swing.JLabel();
        btnPlaylist = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        jpnPrincipal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMusicas = new javax.swing.JList<>();
        txtInfoTitulo = new javax.swing.JLabel();
        txtArtista = new javax.swing.JLabel();
        txtInfoArtista = new javax.swing.JLabel();
        txtGenero = new javax.swing.JLabel();
        txtInfoGenero = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JLabel();
        txtInfoDuracao = new javax.swing.JLabel();
        combolistaPlaylist = new javax.swing.JComboBox<>();
        btnAddMusicaPlaylist = new javax.swing.JButton();
        btnRemoverMusicaPlaylist = new javax.swing.JButton();
        jpnBaixo = new javax.swing.JPanel();
        btnLike = new javax.swing.JButton();
        btnDeslike = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnPlayPause = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        Progresso = new javax.swing.JProgressBar();
        txtTempo = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setToolTipText("");
        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1024, 600));

        jpnCima.setBackground(new java.awt.Color(51, 51, 51));
        jpnCima.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        txtBemVindo.setText("Bem Vindo ####");

        txtfieldPesquisa.setText("O que você quer ouvir?");

        javax.swing.GroupLayout jpnCimaLayout = new javax.swing.GroupLayout(jpnCima);
        jpnCima.setLayout(jpnCimaLayout);
        jpnCimaLayout.setHorizontalGroup(
            jpnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pngSpotifei, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtfieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnCimaLayout.setVerticalGroup(
            jpnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pngSpotifei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfieldPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpnPlaylist.setBackground(new java.awt.Color(102, 102, 102));
        jpnPlaylist.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        listaPlaylist.setBackground(new java.awt.Color(153, 153, 153));
        listaPlaylist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listaPlaylist.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaPlaylist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPlaylist);

        txtPlaylist.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtPlaylist.setForeground(new java.awt.Color(51, 204, 0));
        txtPlaylist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlaylist.setText("SELECIONE A");

        btnInicio.setBackground(new java.awt.Color(51, 51, 51));
        btnInicio.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 204, 0));
        btnInicio.setText("MUSICAS");

        txtPlaylist1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtPlaylist1.setForeground(new java.awt.Color(51, 204, 0));
        txtPlaylist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlaylist1.setText("PLAYLIST");

        btnPlaylist.setBackground(new java.awt.Color(51, 51, 51));
        btnPlaylist.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        btnPlaylist.setForeground(new java.awt.Color(0, 204, 0));
        btnPlaylist.setText("PLAYLIST");
        btnPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaylistActionPerformed(evt);
            }
        });

        btnHistorico.setBackground(new java.awt.Color(51, 51, 51));
        btnHistorico.setFont(new java.awt.Font("Arial", 1, 31)); // NOI18N
        btnHistorico.setForeground(new java.awt.Color(0, 204, 0));
        btnHistorico.setText("HISTORICO");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnPlaylistLayout = new javax.swing.GroupLayout(jpnPlaylist);
        jpnPlaylist.setLayout(jpnPlaylistLayout);
        jpnPlaylistLayout.setHorizontalGroup(
            jpnPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(txtPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPlaylist1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnPlaylistLayout.setVerticalGroup(
            jpnPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlaylist1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        jpnPrincipal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        listaMusicas.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        listaMusicas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaMusicas);

        txtInfoTitulo.setText("Titulo da Musica");

        txtArtista.setText("Artista:");

        txtInfoArtista.setText("Nome do Artista");

        txtGenero.setText("Gênero:");

        txtInfoGenero.setText("Genero da Musica");

        txtDuracao.setText("Duração:");

        txtInfoDuracao.setText("00:00");

        combolistaPlaylist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddMusicaPlaylist.setText("Adicionar");

        btnRemoverMusicaPlaylist.setText("Remover");

        javax.swing.GroupLayout jpnPrincipalLayout = new javax.swing.GroupLayout(jpnPrincipal);
        jpnPrincipal.setLayout(jpnPrincipalLayout);
        jpnPrincipalLayout.setHorizontalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddMusicaPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combolistaPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInfoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtInfoTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(txtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInfoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(txtDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInfoDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemoverMusicaPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnPrincipalLayout.setVerticalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(txtInfoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInfoArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInfoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtInfoDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combolistaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMusicaPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverMusicaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jpnBaixo.setBackground(new java.awt.Color(51, 51, 51));
        jpnBaixo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        btnLike.setText("1");

        btnDeslike.setText("2");

        btnVoltar.setText("3");

        btnPlayPause.setText("4");

        btnProximo.setText("5");

        txtTempo.setText("00:00");

        btnMenu.setText("MENU");

        javax.swing.GroupLayout jpnBaixoLayout = new javax.swing.GroupLayout(jpnBaixo);
        jpnBaixo.setLayout(jpnBaixoLayout);
        jpnBaixoLayout.setHorizontalGroup(
            jpnBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBaixoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeslike, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Progresso, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnBaixoLayout.setVerticalGroup(
            jpnBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBaixoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnLike, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeslike, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlayPause, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Progresso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaylistActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoricoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progresso;
    private javax.swing.JButton btnAddMusicaPlaylist;
    private javax.swing.JButton btnDeslike;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnPlaylist;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnRemoverMusicaPlaylist;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> combolistaPlaylist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnBaixo;
    private javax.swing.JPanel jpnCima;
    private javax.swing.JPanel jpnPlaylist;
    private javax.swing.JPanel jpnPrincipal;
    private javax.swing.JList<String> listaMusicas;
    private javax.swing.JList<String> listaPlaylist;
    private javax.swing.JLabel pngSpotifei;
    private javax.swing.JLabel txtArtista;
    private javax.swing.JLabel txtBemVindo;
    private javax.swing.JLabel txtDuracao;
    private javax.swing.JLabel txtGenero;
    private javax.swing.JLabel txtInfoArtista;
    private javax.swing.JLabel txtInfoDuracao;
    private javax.swing.JLabel txtInfoGenero;
    private javax.swing.JLabel txtInfoTitulo;
    private javax.swing.JLabel txtPlaylist;
    private javax.swing.JLabel txtPlaylist1;
    private javax.swing.JLabel txtTempo;
    private javax.swing.JTextField txtfieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
